name: MountUp
main: com.github.flash619.MountUp.MountUp
version: 0.2.2-SNAPSHOT
load: startup
description: Lets players have mmo styled mounts!
author: Flash619
commands:
  MountUp:
    description: Shows current mount, available mounts, and MountUp Info
    usage: /<command> [info/mount]
  IgnoreMounts:
    description: Makes spawn eggs work as normal by ignoring.
    usage: /<command>
  ClearMounts:
    description: De Spawns your current mount.
    usage: /<command>
