name: MountUp
main: com.github.flash619.MountUp.MountUp
version: 0.2.1-SNAPSHOT
load: startup
description: Lets players have mmo styled mounts!
author: Flash619
commands:
  IgnoreMounts:
    description: Makes spawn eggs work as normal by ignoring.
    usage: /<command>